// Generated by make_data.py from web/session.*.json. Do not edit.
window.DATA = {
 "english": "Today we will start with eigenvalues and eigenvectors.",
 "langs": [
  {
   "code": "hi",
   "native": "हिन्दी",
   "english": "Hindi",
   "text": "आज हम eigenvalues और eigenvectors के साथ शुरू करेंगे।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "ta",
   "native": "தமிழ்",
   "english": "Tamil",
   "text": "இன்று நாம் eigenvalues மற்றும் eigenvectors உடன் தொடங்குவோம்.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "te",
   "native": "తెలుగు",
   "english": "Telugu",
   "text": "ఈ రోజు మనం eigenvalues మరియు eigenvectors తో ప్రారంభిస్తాము.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "kn",
   "native": "ಕನ್ನಡ",
   "english": "Kannada",
   "text": "ಇಂದು ನಾವು eigenvalues ಮತ್ತು eigenvectors ನೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸುತ್ತೇವೆ.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "ml",
   "native": "മലയാളം",
   "english": "Malayalam",
   "text": "ഇന്ന് നാം eigenvalues ഉം eigenvectors ഉം ഉപയോഗിച്ച് തുടങ്ങും.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "ur",
   "native": "اردو",
   "english": "Urdu",
   "text": "آج ہم eigenvalues اور eigenvectors کے ساتھ شروع کریں گے.",
   "rtl": true,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "as",
   "native": "অসমীয়া",
   "english": "Assamese",
   "text": "আজি আমি eigenvalues আৰু eigenvectors ৰ সৈতে আৰম্ভ কৰিম।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "lus",
   "native": "Mizo ṭawng",
   "english": "Mizo",
   "text": "Vawiin hian eigenvalues leh eigenvectors nen kan ṭan dawn a ni.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "mag",
   "native": "मगही",
   "english": "Magahi",
   "text": "आज हम eigenvalues और eigenvectors के साथ शुरू कर देई छी।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "or",
   "native": "ଓଡ଼ିଆ",
   "english": "Odia",
   "text": "ଆଜି ଆମେ eigenvalues ଏବଂ eigenvectors ସହିତ ଆରମ୍ଭ କରିବୁ ।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "sd",
   "native": "سنڌي",
   "english": "Sindhi",
   "text": "اڄ اسان eigenvalues ۽ eigenvectors سان شروع ڪنداسين.",
   "rtl": true,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "ks",
   "native": "کٲشُر",
   "english": "Kashmiri",
   "text": "آج ہم eigenvalues تہٕ eigenvectors سۭتۍ شروع کرِتھ۔",
   "rtl": true,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "pa",
   "native": "ਪੰਜਾਬੀ",
   "english": "Punjabi",
   "text": "ਅੱਜ ਅਸੀਂ eigenvalues ਅਤੇ eigenvectors ਨਾਲ ਸ਼ੁਰੂ ਕਰਾਂਗੇ।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "mai",
   "native": "मैथिली",
   "english": "Maithili",
   "text": "आज हम eigenvalues आ eigenvectors सँ शुरू करब।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "ne",
   "native": "नेपाली",
   "english": "Nepali",
   "text": "आज हामी eigenvalues र eigenvectors को साथ सुरु गर्नेछौं।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "mni",
   "native": "মৈতৈলোন্",
   "english": "Manipuri",
   "text": "ঙসি ঐখোয়না eigenvalues অমসুং eigenvectorsগা হৌরগনি।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "bho",
   "native": "भोजपुरी",
   "english": "Bhojpuri",
   "text": "आज हम eigenvalues अउरी eigenvectors से शुरू करब.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "awa",
   "native": "अवधी",
   "english": "Awadhi",
   "text": "आज हम eigenvalues अउर eigenvectors से शुरू करैं।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "hne",
   "native": "छत्तीसगढ़ी",
   "english": "Chhattisgarhi",
   "text": "आज हम eigenvalues अउ eigenvectors ले शुरू करबो।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "mr",
   "native": "मराठी",
   "english": "Marathi",
   "text": "आज आम्ही eigenvalues आणि eigenvectors सह प्रारंभ करू.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "gu",
   "native": "ગુજરાતી",
   "english": "Gujarati",
   "text": "આજે આપણે eigenvalues અને eigenvectors થી શરૂ કરીશું.",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "code": "bn",
   "native": "বাংলা",
   "english": "Bengali",
   "text": "আজ আমরা eigenvalues এবং eigenvectors দিয়ে শুরু করব।",
   "rtl": false,
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  }
 ],
 "captions": [
  {
   "index": 0,
   "text": "Good morning everyone.",
   "start_s": 0.0,
   "latency_ms": 2231,
   "rtf": 1.025,
   "tr": "सभी को शुभ दोपहर।",
   "terms": []
  },
  {
   "index": 1,
   "text": "Today we will start with eigenvalues and eigenvectors.",
   "start_s": 2.55,
   "latency_ms": 2507,
   "rtf": 0.56,
   "tr": "आज हम eigenvalues और eigenvectors के साथ शुरू करेंगे।",
   "terms": [
    "eigenvectors",
    "eigenvalues"
   ]
  },
  {
   "index": 2,
   "text": "These two ideas sit at the center of linear algebra, so it is worth going slowly.",
   "start_s": 8.09,
   "latency_ms": 2718,
   "rtf": 0.397,
   "tr": "ये दो विचार रैखिक बीजगणित के केंद्र में हैं, इसलिए यह धीमी गति से आगे बढ़ना लायक है।",
   "terms": []
  },
  {
   "index": 3,
   "text": "A matrix is a linear transformation.",
   "start_s": 15.86,
   "latency_ms": 2341,
   "rtf": 0.684,
   "tr": "एक मैट्रिक्स एक रैखिक परिवर्तन है।",
   "terms": []
  },
  {
   "index": 4,
   "text": "It stretches, rotates and shears space.",
   "start_s": 19.58,
   "latency_ms": 2653,
   "rtf": 0.648,
   "tr": "यह खिंचाव, घूमता है और अंतरिक्ष को काटता है।",
   "terms": []
  },
  {
   "index": 5,
   "text": "For most vectors, applying the matrix changes both direction and length.",
   "start_s": 24.76,
   "latency_ms": 2702,
   "rtf": 0.454,
   "tr": "अधिकांश वेक्टरों के लिए, मैट्रिक्स को लागू करने से दिशा और लंबाई दोनों बदल जाती है।",
   "terms": []
  },
  {
   "index": 6,
   "text": "But a few special vectors only change length.",
   "start_s": 31.86,
   "latency_ms": 2727,
   "rtf": 0.722,
   "tr": "लेकिन कुछ विशेष वेक्टर केवल लंबाई बदलते हैं।",
   "terms": []
  },
  {
   "index": 7,
   "text": "Their direction is preserved.",
   "start_s": 35.99,
   "latency_ms": 2278,
   "rtf": 0.89,
   "tr": "उनका मार्गदर्शन संरक्षित है।",
   "terms": []
  },
  {
   "index": 8,
   "text": "Those vectors are the eigenvectors, and the factor they stretch by is the eigenvalue.",
   "start_s": 39.61,
   "latency_ms": 2853,
   "rtf": 0.423,
   "tr": "वेक्टर eigenvectors हैं, और कारक वे द्वारा फैलाव eigenvalue है.",
   "terms": [
    "eigenvectors",
    "eigenvalue"
   ]
  },
  {
   "index": 9,
   "text": "To find them we solve the characteristic equation of the matrix.",
   "start_s": 47.35,
   "latency_ms": 2590,
   "rtf": 0.525,
   "tr": "उन्हें खोजने के लिए हम मैट्रिक्स के विशिष्ट समीकरण को हल करते हैं।",
   "terms": []
  },
  {
   "index": 10,
   "text": "The determinant of a minus lambda times the identity must equal zero.",
   "start_s": 53.27,
   "latency_ms": 2511,
   "rtf": 0.454,
   "tr": "एक शून्य lambda के determinant पहचान 0 के बराबर होना चाहिए।",
   "terms": [
    "determinant"
   ]
  },
  {
   "index": 11,
   "text": "The determinant is a single number that tells you whether the matrix squashes space flat.",
   "start_s": 59.8,
   "latency_ms": 2572,
   "rtf": 0.416,
   "tr": "determinant एक एकल संख्या है जो आपको बताता है कि मैट्रिक्स अंतरिक्ष सपाट squashes है।",
   "terms": [
    "determinant"
   ]
  },
  {
   "index": 12,
   "text": "If it is zero, there is a non-trivial solution, and that is exactly what we want.",
   "start_s": 67.03,
   "latency_ms": 2809,
   "rtf": 0.392,
   "tr": "यदि यह शून्य है, तो एक गैर-नाजुक समाधान है, और यही हम चाहते हैं।",
   "terms": []
  },
  {
   "index": 13,
   "text": "Symmetric matrices always have real eigenvalues.",
   "start_s": 75.32,
   "latency_ms": 2508,
   "rtf": 0.572,
   "tr": "सममित मैट्रिक्स हमेशा असली eigenvalues है।",
   "terms": [
    "eigenvalues"
   ]
  },
  {
   "index": 14,
   "text": "That is a useful guarantee.",
   "start_s": 79.93,
   "latency_ms": 2470,
   "rtf": 0.93,
   "tr": "यह एक उपयोगी गारंटी है।",
   "terms": []
  },
  {
   "index": 15,
   "text": "Once we have a full set of eigenvectors, we can diagonalize the matrix.",
   "start_s": 83.61,
   "latency_ms": 2668,
   "rtf": 0.437,
   "tr": "एक बार जब हम eigenvectors का पूरा सेट है, हम diagonalize कर सकते हैं मैट्रिक्स.",
   "terms": [
    "eigenvectors",
    "diagonalize"
   ]
  },
  {
   "index": 16,
   "text": "Diagonalization turns a hard repeated multiplication into a simple one.",
   "start_s": 90.71,
   "latency_ms": 2662,
   "rtf": 0.455,
   "tr": "डायग्नोलेशन एक कठिन दोहराया गुणन को एक सरल में बदल देता है।",
   "terms": []
  },
  {
   "index": 17,
   "text": "We will use this next week when we look at principal component analysis.",
   "start_s": 97.62,
   "latency_ms": 2599,
   "rtf": 0.486,
   "tr": "हम अगले सप्ताह इसका उपयोग करेंगे जब हम मुख्य घटक विश्लेषण को देखते हैं।",
   "terms": []
  }
 ],
 "gloss": [
  {
   "term": "eigenvalue",
   "explanation": "A scalar showing how much a matrix stretches a special direction (its eigenvector).",
   "backend": "heuristic",
   "latency_ms": 0
  },
  {
   "term": "eigenvector",
   "explanation": "A direction that a matrix only stretches or shrinks, without rotating it.",
   "backend": "heuristic",
   "latency_ms": 0
  },
  {
   "term": "determinant",
   "explanation": "A single number from a square matrix; zero means the matrix squashes space flat.",
   "backend": "heuristic",
   "latency_ms": 0
  },
  {
   "term": "diagonalize",
   "explanation": "Rewriting a matrix in a basis where it becomes a simple diagonal scaling.",
   "backend": "heuristic",
   "latency_ms": 0
  }
 ]
};
