"""Pull the film's real material out of the recorded sessions into data.js.

Everything the reel shows as product output comes from here, unedited: the
Hindi session's captions, translations, timings and jargon entries, and the
same English line as all 22 recordings translated it.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WEB = ROOT / "web"
OUT = Path(__file__).resolve().parent / "data.js"

# The line every recording shares, and the order the reel spins through them.
ANCHOR_INDEX = 1
# Long lines pass in the fast part of the spin; the slow landing is on lines that fit the frame whole.
ORDER = ["hi", "ta", "te", "kn", "ml", "ur", "as", "lus", "mag", "or", "sd",
         "ks", "pa", "mai", "ne", "mni", "bho", "awa", "hne", "mr", "gu", "bn"]
RTL = {"ur", "ks", "sd"}


def load(code):
    return json.loads((WEB / f"session.{code}.json").read_text(encoding="utf-8"))


def main():
    names = {lang["code"]: lang["name"] for lang in json.loads((WEB / "static" / "languages.json").read_text(encoding="utf-8"))}
    langs = []
    for code in ORDER:
        s = load(code)
        tr = {e["index"]: e for e in s["events"] if e["kind"] == "translation"}[ANCHOR_INDEX]
        native, english = names[code].rsplit(" (", 1)
        langs.append({"code": code, "native": native, "english": english.rstrip(")"),
                      "text": tr["text"], "rtl": code in RTL, "terms": tr["protected_terms"]})

    hi = load("hi")
    caps = {e["index"]: e for e in hi["events"] if e["kind"] == "caption"}
    trs = {e["index"]: e for e in hi["events"] if e["kind"] == "translation"}
    captions = []
    for i in sorted(caps):
        c, t = caps[i], trs.get(i)
        captions.append({"index": i, "text": c["text"], "start_s": c["start_s"],
                         "latency_ms": round(c["latency_ms"]), "rtf": c["rtf"],
                         "tr": t["text"] if t else "", "terms": t["protected_terms"] if t else []})
    gloss = [{"term": e["term"], "explanation": e["explanation"], "backend": e.get("backend", ""),
              "latency_ms": round(e.get("latency_ms", 0))} for e in hi["events"] if e["kind"] == "gloss"]

    data = {"english": caps[ANCHOR_INDEX]["text"], "langs": langs, "captions": captions, "gloss": gloss}
    OUT.write_text("// Generated by make_data.py from web/session.*.json. Do not edit.\nwindow.DATA = "
                   + json.dumps(data, ensure_ascii=False, indent=1) + ";\n", encoding="utf-8")
    print(f"{OUT.name}: {len(langs)} languages, {len(captions)} captions, {len(gloss)} glossary entries")


if __name__ == "__main__":
    main()
